# Generated by Django 4.2.4 on 2023-11-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0007_comment_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
