# Generated by Django 4.2.4 on 2023-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
