# Generated by Django 4.2.4 on 2023-11-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0011_commentreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
