# Generated by Django 4.2.4 on 2023-11-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0014_remove_comment_parent_comment_commentreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='parent_comment',
            new_name='child_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_forums.comment'),
        ),
    ]
