# Generated by Django 4.2.4 on 2023-11-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0019_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
