# Generated by Django 4.2.4 on 2023-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0020_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(default='2022-03-22 1:14'),
        ),
    ]
